version: '3.8'

services:
  it_conference:
    container_name: ITConference
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: conferencedb
      POSTGRES_USER: conference
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - conference:/var/lib/postgresql/data
volumes:
  conference: